function createfigure(X1, YMatrix1, X2, Y1, YMatrix2, degree)
%CREATEFIGURE1(X1, YMATRIX1, X2, Y1, YMATRIX2)
%  X1:  vector of x data
%  YMATRIX1:  matrix of y data
%  X2:  vector of x data
%  Y1:  vector of y data
%  YMATRIX2:  matrix of y data

%  Auto-generated by MATLAB on 29-Nov-2018 19:56:20

% Create figure
figure1 = figure('Position', [10 36 628 623]);

% Create axes
axes1 = axes('Parent',figure1,'FontSize',14,'FontName','Arial',...
    'Position',[0.144705882352941 0.414089347079038 0.773047091412741 0.489951056961366],...
    'XTickLabel','');
box(axes1,'on');
hold(axes1,'on');

% Create multiple lines using matrix input to plot
plot1 = plot(X1,YMatrix1,'Parent',axes1);
set(plot1(1),'DisplayName','Data','Marker','.','LineStyle','none',...
    'Color',[0 0 0]);
set(plot1(2),'DisplayName','Linear Fit','LineWidth',2,...
    'Color',[1 0.200000002980232 0.200000002980232]);
set(plot1(3),'DisplayName','95% Prediction Interval','LineWidth',1.5,...
    'LineStyle','--',...
    'Color',[0 1 0]);
set(plot1(4),'DisplayName','data1','LineWidth',2,'LineStyle',':',...
    'Color',[0 1 0]);

% Create plot
plot(X2,Y1,'Parent',axes1,'DisplayName',['Max DM ~' num2str(X2)],...
    'MarkerFaceColor',[1 1 0],...
    'MarkerEdgeColor',[0 0 0],...
    'MarkerSize',9,...
    'Marker','o',...
    'LineStyle','none');

% Create ylabel
ylabel('Signal to Noise (mJy)','FontSize',15.4);

% Create title
title({'Disperiosn Measure vs S/N',...
    ['Polynomial fit with degree:' num2str(degree)]},...
    'FontSize',15.4);

% Create legend
legend1 = legend(axes1,'show');
set(legend1,...
    'Position',[0.541064679355357 0.758377967082995 0.377450971870251 0.146532434478435]);

% Create axes
axes2 = axes('Parent',figure1,'FontSize',14,'FontName','Arial',...
    'Position',[0.139803921568628 0.0948484848484848 0.775 0.281752577319588]);
box(axes2,'on');
hold(axes2,'on');

% Create multiple lines using matrix input to plot
plot2 = plot(X1,YMatrix2,'Parent',axes2);
set(plot2(1),'Marker','.','LineStyle','none','Color',[0 0 0]);
set(plot2(2),'LineWidth',2,'Color',[1 0 0]);

% Create xlabel
xlabel('Dispersion Measure (pc/cm^{-3})','FontSize',15.4);

% Create ylabel
ylabel('Residuals (mJy) ','FontSize',15.4);

